# default
spring:
  config:
    import:
      - classpath:/yaml/application-prod.yml
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-secret.yml
      - classpath:/yaml/application-file.yml

  profiles:
    active: local #default
    group:
      local:
        - secret
        - file # local + secret + file 실행
      dev:
        - secret
        - file
      prod:
        - secret
        - file
---
spring:
  config:
    activate:
      on-profile: local # local + secret 실행
---
spring:
  config:
    activate:
      on-profile: dev # dev + secret
---
spring:
  config:
    activate:
      on-profile: prod # prod + secret