spring:
  config:
    activate:
      on-profile: file

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

file:
  allowed-extensions: jpg,jpeg,png
  mainPhoto-dir: src/main/resources/static/mainPhoto
  introPhoto-dir: src/main/resources/static/introPhoto
  noticePhoto-dir: src/main/resources/static/noticePhoto